baseURL = "http://nevergetoffthebus.blog/"
languageCode = "en-us"
title = "never get off the bus"
theme = "smol"
[markup.goldmark.renderer]
unsafe = true

[params]
subtitle = "As the world goes to shit, del amitri get back on the bus."
description = "a US tour diary "
author = "Ebo H"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "recent work"
        url = "https://iainharvie.com"
        weight = 1

  [[menu.footer]]
        name = "DAAS"
        url = "https://delamitriareshite.com"
        weight = 2

  [[menu.footer]]
        name = "play when people are listening"
        url = "https://playwhenpeoplearelistening.com"
        weight = 3 

 