#+hugo_base_dir: ../
#+hugo_section: ./posts
#+hugo_weight: auto
#+hugo_auto_set_lastmod: t

#+author: Ebo H

* Post template                                                    :noexport:
:PROPERTIES:
:EXPORT_FILE_NAME: post-file-name
:EXPORT_DATE: 2023-01-01
:EXPORT_HUGO_MENU: :menu "main"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:
:END:


* Never get off the bus                                               :@Journal:
** DONE Get back on the bus                                           :dels:
:PROPERTIES:
:EXPORT_FILE_NAME: never-say-never
:EXPORT_DATE: 2022-03-25
:EXPORT_HUGO_MENU: :menu "main"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:
:END:
And so it goes. Never say never. Back to the interstates again after all these years to do a month of shows.

** DONE Tip the world over on its side and everything loose will land in Los Angeles.
:PROPERTIES:
:EXPORT_FILE_NAME: tip-the-world-over-on-its-side-and-everything-loose-will-land-in-los-angeles
:EXPORT_DATE: 2022-03-25
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:
:END:
In that   weird liminal space—11 hours, 9000 meters above an ocean moving at nearly 1000kmh kilometres an hour in an intercontinental ballistic people carrier, after hours of waiting and moving through the non-spaces of airport terminals, now travelling back through the day to arrive not long after leaving, there seems to be nothing to think, nothing to consider except how to stay calm stuck in the same seat for half a day and the sheer implausibility of a 250 tonne airliner with three hundred people on board taking to the skies.

Back to the United States of America, after so long. Back to Los Angeles (the home of the sadly missed A&M records and still, somehow, Del Amitri’s spiritual home in the US) to get on a bus for a month of shows that will take us across the continent: from Los Angeles into the desert to Phoenix, north to Berkeley and Seattle and on to Vancouver; over the mountains to Colorado and back north to Milwaukee; through the mid-west via Toronto to the east coast, to Vermont and New York City, North Carolina and Atlanta, and finally to western Pennsylvania and Ohio.

If Herb Alpert and Gerry Moss (and Al Cafaro, Brad and Barbara and Al and all those lovely people at A&M) gave us a spiritual US home in Los Angeles, Del Amitri’s heart was stolen on the road: in a car park in Louisville Kentucky, under a freeway in Jackson Mississippi, on Daytona Beach; at Shank Hall, the Double Door, the 9:30 Club, St. Andrews Hall (even at Rome 90 where it wasn't clear if there was actually anyone in the audience at the show). It was stolen by all the people who come to see us at concerts in Boulder, in New York City, in Dallas and in New Orleans, in Minneapolis and in Chicago (remembering of course dear Ross Greirson, gone but not forgotten) and the hundred other towns we made it to. 

So much seems to have changed since we recorded Fatal Mistakes (never mind since we last toured in the US). From where I am sat for the next 11 hours it is hard not to gaze out into the sky and wonder about the world nine kilometres below, a world that seems to be crumbling in humanity’s collective hands.

Comprehending the complex aerodynamics that are keeping the 250 tonnes in the air at the moment starts to look like a puny challenge in the face of trying to make sense of the complacent inhumanity to fellow beings and the willful negligence of the planet that twenty first century homo sapiens seems capable of. Disaster capitalism prevails: nationalist wars, ethnic cleansing, disease, poverty, global warming continue to bring catastrophe to countless millions while the super rich bicker amongst themselves and thrive.

And when intelligent beings think and plan and sustain war it is almost impossible no to sink into cynicism about politics and progress towards a peaceful and equitable society. 

On one level it feels complacent, or even complicit to be business-as-usual in the face of what is going down around us (not that anything actually is ‘business as usual’ for any of us at the moment—except perhaps for the Musks and Bezoss of the planet). 

We have crossed an ocean. Nine kilometres below I can see a mind-blowingly enormous glacier. Temperatures at the south pole were 50 degrees above average last week. The plane I am flying in is a direct cause of that glacier melting. But would it make any difference if I stayed at home? Does the carbon footprint of men who spend billions to fly in to space for shits and giggles make a transatlantic flight to work for a month on the other side of the planet OK?

If, as the cliche goes, travel broadens the mind (why does Jeff Bezos have such a tiny head then?) then touring focuses your efforts. If nothing else touring is grounding. So much effort from so many people goes into making a show 9000 miles from home even happen.

There is only one thing that you have to get right: that evening’s show. When it is right and we get to play and there are people there to listen to the music we make, something happens. Something that makes me glad to be alive. Glad to be alive in the most self-centred, solipsistic sense, sure, but also profoundly glad to be with people. People I know and people I don’t know and might never meet again, people who might hold different beliefs from me about almost everything in the world apart from what is going on in that room for a brief couple of hours. Collectively, the pessimism seems to ease (even if the music might be openly pessimistic—watching The Fall night on a brief Scottish tour was a visceral and life-affirming experience; the two classic Joy Division records are, because of and not in spite of their bleakness, like consoling old friends that I have conversed with for forty years). The cloud of disaster seems marginally more remote for a while. 

I always felt reassured that devoting my labour to writing and playing music was at least a way to disengage with ‘the system’ and at best, by disengaging, a form of protest even if the music Del Amitri make is not, on the surface at least, protest music. Maybe it would be better if all music was overtly political but somehow for me that breaks the spell: ``You are either with us or against us''---cynicism is back in the room. There are times and places where there is no choice but to be militant, to call for action and to take action against what is unquestionably immoral and wrong. Those times and places seem more urgent and more frequent now that I have ever known.

And in the face of this we bring our little roadshow to travel across that implausibly great and implausibly flawed continent that is North America. Not because we can’t think of anything better to do in the face of the shit that is flying around us all, but to feel alive and to share that feeling. And because we love it.

** DONE LAX to Hollywood
:PROPERTIES:
:EXPORT_FILE_NAME: lax-to-hollywood
:EXPORT_DATE: 2022-03-25
:EXPORT_HUGO_MENU: :menu "main"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:
:END:
The driver that picks us up at LAX to deliver us to the hotel at Hollywood and Highland—the centre of very deepest circle of  Los Angeles—is a gentle spoken bear of a man named, appropriately enough, Virgil. He swaps his cowboy hat for an ominously Trumpian red baseball cap as he gets into the driving seat but I can't see the front of it as he drives. Virgil has his phone guide the Econoline via a commodious route through the steam-rollered smorgasbord of Los Angeles culture on freeways that take us past the The Getty and Universal City.
Like all real southern gentlemen Virgil engages effortlessly in conversation. I am riding shotgun—in the conversation seat—but just off the plane I haven’t yet got used to tempering my accent for stateside consumption and out of necessity the exchange ends up being pretty much one-way. By the time we pull of the Hollywood freeway I know a lot about Virgil.

Virgil is from rural Louisiana. He was born in 1957, worked as a truck driver until he retired in 2007 on health grounds. Since then he has recovered from two consecutive cancers each of which his doctors told him would kill him. But he told those doctors he would beat those cancers, and he did. He just started work again as a limo driver (which maybe explains why he hasn't had Samantha SatNav's soothing voice direct him on the much shorter route through downtown LA). He had his right knee done last year by the same orthopaedic surgeon that fixed Shaq O’Neal. He has just discovered two brothers he didn’t know he had and is planning to ride his new Indian bike on a four day road trip clear across the continent this summer to Maryland to meet them for the first time.  He doesn’t like flying. (But who does—-- and what kind of right-minded person would choose to fly over spending four days on the open road through deserts and over mountains on their Indian motorcycle?). Once we pull into the hotel car park Virgil swaps his hats again. I forgot to look to see what was embroidered on the front of the baseball cap. I’m sure there must be a basketball team in Louisiana who play in red. Maybe not. Maybe some MAGA people are real human beings.
 

** DONE Chandler no more, Bukowski no more.
:PROPERTIES:
:EXPORT_FILE_NAME: chandler-no-more-bukowski-no-more
:EXPORT_DATE: 2022-03-25
:EXPORT_HUGO_MENU: :menu "main"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:
:END:
The nearest place to the hotel to eat is Mel’s Diner. Buddy, Brian and I drift
down there in an effort to stay awake and head off the looming jet-lag as much
as by a desire for a Mel’s 3-Deck Club Sandwich.

Hollywood has fully mutated into a tourist theme park. Grauman's Chinese Theatre
has been swallowed up by the Ovation Hollywood shopping mall, a piece of instant
architecture that covers half a block and insults the street on every
conceivable aspect with three-storey-high digital billboards—--I assume there are
football pitch sized screens on the roof directed at passing aircraft. The
Oscars are in town and there is a covered catwalk the length of an entire block
on Hollywood Boulevard guarded by an army of security staff who have nothing to
do but stand around the structure trying to look purposeful. Every piece of
spare asphalt has a TV truck parked on it. Thankfully we will be in Phoenix with
300 miles of desert between us and Hollywood when the madness unfolds on Sunday
night.

Mel’s Hollywood Drive-In wants to seem like it has been there since 1947, but
actually opened in 2001 which explains why the dining experience is that of
eating on a recently constructed film set. Anything now remaining of the City of
Dreams has been torn down and replaced or spruced for the tourists and looks so
like new that it makes no difference. But then again, any concept of ‘authentic’
Hollywood is completely fucking absurd in the first place.

Justin has had the same idea as us and wanders in five minutes behind us and we
all order some kind of diner cliche; Fried Chicken, Reuben, Steak Sandwich.
There are a couple of the LAPD sitting at the counter and another four join them
while we eat.

Post-flight and pre jet-lag, no one at our table is remotely capable of engaging
conversation. The cops are right in my line of sight and I distractedly
people-watch them as I eat my ‘Mel’s Famous Haven Sandwich’; they all have great
haircuts, their uniforms all fit like Saville Row suits and their shock-and-awe
side-arms and the myriad of other military looking equipment that festoons them
looks like it was made to co-ordinate in the military-industrial-complex
department of Gucci. They are super polite to the waiters and to each other.
It’s hard to imagine them making ever handing out a speeding ticket never mind
making a drugs bust, but I suppose that working for the LAPD is a job for life
and maybe South Central LA has changed a bit since the nineties. And, I suppose,
the rozzers policing this block of Hollywood during Oscar’s week are probably
hand picked for different qualities than those battalioned in Watts to keeps the
Crips and the Bloods in line. As they leave they very naturally line up like a
rock band for a photo for the staff.

The creeping sense of verisimilitude that Mel’s is instilling gets more intense
with the dawning realisation that the reason these look like they might have
been chosen by a casting agent is because they /were/ chosen by a casting agent:
these aren’t hard-bitten cops out to protect and to serve the incoming Academy
Award’s nominees—these are the cast of some cop show on a night shoot fresh out
of the costume department. That’s why the shiny new radios are silent, why the
weapons look like they have never been fired, why there isn’t a line of LAPD
cruisers out front, why they were all so unbelievably polite. Is everyone in
Mel’s, everyone in Hollywood, actually an actor reading from a script for our
benefit? Sleep deprivation drives us back to the relative safety of the Holiday
Inn Suites.


* Footnotes
* Local Variables                                           :noexport:
org-hugo-footer: "\n\n[//]: # \"with love from the end of the world\"" End:
